/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import audiorecognizer.*;
import v2d.*;


/**
 *
 * @author Seraph
 */
public class gui extends javax.swing.JFrame {
 int xm,ym;
    /**
     * Creates new form gui
     */
    public gui() {
         setIcon();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_normal.png"))); // NOI18N
        jLabel8.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nClose\n</B></FONT></html>");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 34, 90, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question_normal.png"))); // NOI18N
        jLabel7.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nHelp\n</B></FONT></html>");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 100, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/srs_normal.png"))); // NOI18N
        jLabel6.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nSoftware Requirements Specification\n</B></FONT></html>");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 34, 90, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimise_normal.png"))); // NOI18N
        jLabel5.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nMinimize\n</B></FONT></html>");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 36, 90, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book_normal.png"))); // NOI18N
        jLabel4.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nReadMe\n</B></FONT></html>");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 36, 90, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playoriginalfinal.png"))); // NOI18N
        jLabel2.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nWatch Your Movies With Subtitles\n</B></FONT></html>");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 200, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light_normal.png"))); // NOI18N
        jLabel3.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nQuery or Suggestion\n</B></FONT></html>");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 36, 90, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/body_normal.png"))); // NOI18N
        jLabel1.setToolTipText("<html><B><FONT FACE=\"TIMES NEW ROMAN \" COLOR=\"RED\">\nAutomatic Subtitle Generator\n</B></FONT></html>");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1200, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     /*ImageIcon ii=new ImageIcon(getClass().getResource("/Images/close_mouseclicked"));
    jLabel8.setIcon(ii); */
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
ImageIcon ii=new ImageIcon(getClass().getResource("/Images/close_mouseentered.png"));
    jLabel8.setIcon(ii);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
ImageIcon ii=new ImageIcon(getClass().getResource("/Images/close_normal.png"));
    jLabel8.setIcon(ii);              // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        this.setState(gui.ICONIFIED); 
    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
      ImageIcon ii=new ImageIcon(getClass().getResource("/Images/minimise_mouseentered.png"));
    jLabel5.setIcon(ii);                 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/minimise_normal.png"));
    jLabel5.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/netbeans.gif"));
    jLabel2.setIcon(ii);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      JFileChooser ch=new JFileChooser();
        
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("mp4");
       // ch.setFileFilter(filter);
       ch.showOpenDialog(null);
              File f=ch.getSelectedFile();
              
              String filename=f.getAbsolutePath();
     
        
    
           
      try {
         Main.v2dmain(filename);
         /*try {
         java.awt.Desktop.getDesktop().open(f);
         } catch (IOException ex) {
         Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
         }  */     // TODO add your handling code here:
     } catch (IOException ex) {
         Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/playoriginalfinal.png"));
    jLabel2.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
File f=new File("J:\\Automatic Subtitle Generator\\src\\Files\\Help.txt");
        try {
            java.awt.Desktop.getDesktop().open(f);
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }   
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/question_mouseclicked.png"));
    jLabel7.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/question_mouseentered.png"));
    jLabel7.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/question_normal.png"));
    jLabel7.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
     File f=new File("J:\\Automatic Subtitle Generator\\src\\Files\\SRS.pdf");
        try {
            java.awt.Desktop.getDesktop().open(f);
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }    
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/srs_mouseclicked.png"));
    jLabel6.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/srs_mouseentered.png"));
    jLabel6.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/srs_normal.png"));
    jLabel6.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       /*File f=new File("https://www.facebook.com/automaticsubtitlegenerator/?fref=ts.html");
        try {
            java.awt.Desktop.getDesktop().open(f);
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        } */            
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/light_mouseclicked.png"));
    jLabel3.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/light_mouseenteredoriginal.png"));
    jLabel3.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/light_normal.png"));
    jLabel3.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
File f=new File("J:\\Automatic Subtitle Generator\\dist\\javadoc\\index.html");
        try {
            java.awt.Desktop.getDesktop().open(f);
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }  
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/book_mouseclicked.png"));
    jLabel4.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/book_mouseentered.png"));
    jLabel4.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/book_normal.png"));
    jLabel4.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/body_mouseentered.png"));
    jLabel1.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
       ImageIcon ii=new ImageIcon(getClass().getResource("/Images/body_normal.png"));
    jLabel1.setIcon(ii); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        /*xm1=evt.getX();
     ym1=evt.getY(); */
   ImageIcon ii=new ImageIcon(getClass().getResource("/Images/play_mouseclicked.png"));
    jLabel2.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
 ImageIcon ii=new ImageIcon(getClass().getResource("/Images/playoriginalfinal.png"));
    jLabel2.setIcon(ii);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
ImageIcon ii=new ImageIcon(getClass().getResource("/Images/mimimise_mouseclicked.png"));
    jLabel5.setIcon(ii);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
ImageIcon ii=new ImageIcon(getClass().getResource("/Images/minimise_normal.png"));
    jLabel5.setIcon(ii);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        ImageIcon ii=new ImageIcon(getClass().getResource("/Images/close_mouseclicked.png"));
    jLabel8.setIcon(ii);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
   xm=evt.getX();
   ym=evt.getY(); 
   //System.out.println(xm); 
   //System.out.println(ym);
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
int x=evt.getXOnScreen();
int y=evt.getYOnScreen();
this.setLocation(x-xm,y-ym);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
/*int x1=evt.getXOnScreen();
int y1=evt.getYOnScreen();
this.setLocation(x1-xm1,y1-ym1);  */      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui nj=new gui();
                //nj.setSize(800,500);
                nj.setIcon();
                nj.setBackground(new Color(0, 0, 0, 0));
                nj.setVisible(true);
                //new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/icon.png")));
    }
}
